export const ROUTES = {
    HOME: '/',
    NOTFOUND: '*',
    PILOTENINFO: '*',
    INFORMATIONEN: '/informationen',
    FLUGAUSBILDUNG: '/flugausbildung',
    MOTORFLUG: '/flugausbildung/motorflug',
    SEGELFLUG: '/flugausbildung/segelflug',
    ULTRALEICHTFLUG: '/flugausbildung/ultraleichtflug',
    CHRONIK: '/chronik',
    FLUGZEUGE: '/flugzeuge',
    CESSNA: '/flugzeuge/cessna',
    ROBIN: '/flugzeuge/robin',
    DYNAMIC: '/flugzeuge/dynamic',
    PIONEER: '/flugzeuge/pioneer',
    ASK21: '/flugzeuge/ask21',
    DISCUS: '/flugzeuge/discus',
    ASW20: '/flugzeuge/asw20',
    RUNDFLUEGE: '/rundfluege',
    GUTSCHEINE: '/rundfluege#gutscheine',
    FOTOS: '/fotos',
    IMPRESSUM: '/kontakt',
    KONTAKT: '/kontakt',
    DATENSCHUTZ: '/datenschutz',
    WEBCAM_OST: '/webcam-ost',
    WEBCAM_SUED: '/webcam-sued',
  };
  
